# Config example for Argentinian License Plates
# The old license plates contain 6 slots/characters (i.e. JUH697)
# and new 'Mercosur' contain 7 slots/characters (i.e. AB123CD)

# Max number of plate slots supported. This represents the number of model classification heads.
max_plate_slots: 7
# All the possible character set for the model output.
alphabet: '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_'
# Padding character for plates which length is smaller than MAX_PLATE_SLOTS. It should still be present in the alphabet.
pad_char: '_'
# Image height which is fed to the model.
img_height: 70
# Image width which is fed to the model.
img_width: 140
